baseURL = 'https://hey.iamyourjun.com/'

languageCode = 'en-us'
hasCJKLanguage = true
enableEmoji = true

# relativeURLs = true
# canonifyURLs = true

title = 'Junbeom In'
copyright = 'Â© 2025 Junbeom In'

timeZone = "America/New_York"

theme = "terminal"

# GITHUB PAGE
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# THEME
[markup.highlight]
  noClasses = false

[params]
  autoCover = false
  fullWidthTheme = true
  centerTheme = true
  showLanguageSelector = false

  [params.logo]
        logoText = "Junbeom In"
        logoHomeLink = "/"
    

# MENU
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Contacts'
    pageRef = '/contacts/'
    weight = 20
  [[menus.main]]
    name = 'Credentials'
    pageRef = '/credentials/'
    weight = 30
  [[menus.main]]
    name = 'Tips'
    pageRef = '/tips/'